version: "3.8"

services:
  # n8n 서비스
  n8n:
    build:
      context: .
      dockerfile: n8n/Dockerfile  # n8n의 Dockerfile을 사용하여 빌드
    container_name: n8n
    ports:
      - "5678:5678"  # n8n 웹 UI 접근을 위한 포트 매핑
    volumes:
      - ./n8n:/root/.n8n  # n8n 데이터 저장소
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user  # 인증용 사용자
      - N8N_BASIC_AUTH_PASSWORD=password  # 인증용 비밀번호
      - GOOGLE_APPLICATION_CREDENTIALS=/home/node/.n8n/brieflab_service_account.json  # Google 인증
    restart: unless-stopped  # 컨테이너가 중지되면 재시작

  # FastAPI 서비스
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile  # FastAPI의 Dockerfile을 사용하여 빌드
    container_name: fastapi
    ports:
      - "8000:8000"  # FastAPI 포트
    volumes:
      - ./src:/app  # FastAPI 애플리케이션 코드
    environment:
      - ENV=production  # 환경 설정
    restart: unless-stopped  # 컨테이너가 중지되면 재시작

